//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.17929.
// 
namespace Axis1Case1
{

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
	[System.Web.Services.WebServiceBindingAttribute(Name = "EchoEndpointDocumentEncoded12SoapBinding", Namespace = "http://codefirst.case1.axis1.ws.springframework.org")]
	public interface IEchoEndpointDocumentEncoded12SoapBinding
	{

		/// <remarks/>
		[System.Web.Services.WebMethodAttribute()]
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("oneParam", RequestNamespace = "", ResponseNamespace = "", Use = System.Web.Services.Description.SoapBindingUse.Encoded, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare)]
		[return: System.Xml.Serialization.SoapElementAttribute("oneParamReturn")]
		string oneParam(string param1);

		/// <remarks/>
		[System.Web.Services.WebMethodAttribute()]
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("twoParams", RequestNamespace = "", ResponseNamespace = "", Use = System.Web.Services.Description.SoapBindingUse.Encoded, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare)]
		[return: System.Xml.Serialization.SoapElementAttribute("twoParamsReturn")]
		string twoParams(string param1, string param2);
	}

}