//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsmxWebServices.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://axis1.org/ws/services/EchoEndpointDocumentEncoded12")]
        public string AsmxWebServices_DocumentEncoded12_EchoEndpointService {
            get {
                return ((string)(this["AsmxWebServices_DocumentEncoded12_EchoEndpointService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://axis1.org/ws/services/EchoEndpointDocumentLiteral12")]
        public string AsmxWebServices_DocumentLiteral12_EchoEndpointService {
            get {
                return ((string)(this["AsmxWebServices_DocumentLiteral12_EchoEndpointService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://axis1.org/ws/services/EchoEndpointRpcEncoded12")]
        public string AsmxWebServices_RpcEncoded12_EchoEndpointService {
            get {
                return ((string)(this["AsmxWebServices_RpcEncoded12_EchoEndpointService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://axis1.org/ws/services/EchoEndpointRpcLiteral12")]
        public string AsmxWebServices_RpcLiteral12_EchoEndpointService {
            get {
                return ((string)(this["AsmxWebServices_RpcLiteral12_EchoEndpointService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://axis1.org/ws/services/EchoEndpointWrappedLiteral12")]
        public string AsmxWebServices_WrappedLiteral12_EchoEndpointService {
            get {
                return ((string)(this["AsmxWebServices_WrappedLiteral12_EchoEndpointService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://axis1.org/ws/services/EchoEndpointDocumentEncoded12")]
        public string AsmxWebServices_Axis1Case2DocumentEncoded12_EchoEndpointService {
            get {
                return ((string)(this["AsmxWebServices_Axis1Case2DocumentEncoded12_EchoEndpointService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://axis1.org/ws/services/EchoEndpointDocumentLiteral12")]
        public string AsmxWebServices_Axis1Case2DocumentLiteral12_EchoEndpointService {
            get {
                return ((string)(this["AsmxWebServices_Axis1Case2DocumentLiteral12_EchoEndpointService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://axis1.org/ws/services/EchoEndpointRpcEncoded12")]
        public string AsmxWebServices_Axis1Case2RpcEncoded12_EchoEndpointService {
            get {
                return ((string)(this["AsmxWebServices_Axis1Case2RpcEncoded12_EchoEndpointService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://axis1.org/ws/services/EchoEndpointRpcLiteral12")]
        public string AsmxWebServices_Axis1Case2RpcLiteral12_EchoEndpointService {
            get {
                return ((string)(this["AsmxWebServices_Axis1Case2RpcLiteral12_EchoEndpointService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://axis1.org/ws/services/EchoEndpointWrappedLiteral12")]
        public string AsmxWebServices_Axis1Case2WrappedLiteral12_EchoEndpointService {
            get {
                return ((string)(this["AsmxWebServices_Axis1Case2WrappedLiteral12_EchoEndpointService"]));
            }
        }
    }
}
