sed -n '1p'  axis1.log > documentLiteral11plainarrays-req.xml
sed -n '2p'  axis1.log > documentLiteral11plainarrays-res.xml
sed -n '3p'  axis1.log > documentLiteral11wrappedarrays-req.xml
sed -n '4p'  axis1.log > documentLiteral11wrappedarrays-res.xml
sed -n '5p'  axis1.log > documentLiteral12plainarrays-req.xml
sed -n '6p'  axis1.log > documentLiteral12plainarrays-res.xml
sed -n '7p'  axis1.log > documentLiteral12wrappedarrays-req.xml
sed -n '8p'  axis1.log > documentLiteral12wrappedarrays-res.xml
sed -n '9p'  axis1.log > documentEncoded11plainarrays-req.xml
sed -n '10p' axis1.log > documentEncoded11plainarrays-res.xml
sed -n '11p' axis1.log > documentEncoded11wrappedarrays-req.xml
sed -n '12p' axis1.log > documentEncoded11wrappedarrays-res.xml
sed -n '13p' axis1.log > documentEncoded12plainarrays-req.xml
sed -n '14p' axis1.log > documentEncoded12plainarrays-res.xml
sed -n '15p' axis1.log > documentEncoded12wrappedarrays-req.xml
sed -n '16p' axis1.log > documentEncoded12wrappedarrays-res.xml
sed -n '17p' axis1.log > rpcLiteral11plainarrays-req.xml
sed -n '18p' axis1.log > rpcLiteral11plainarrays-res.xml
sed -n '19p' axis1.log > rpcLiteral11wrappedarrays-req.xml
sed -n '20p' axis1.log > rpcLiteral11wrappedarrays-res.xml
sed -n '21p' axis1.log > rpcLiteral12plainarrays-req.xml
sed -n '22p' axis1.log > rpcLiteral12plainarrays-res.xml
sed -n '23p' axis1.log > rpcLiteral12wrappedarrays-req.xml
sed -n '24p' axis1.log > rpcLiteral12wrappedarrays-res.xml
sed -n '25p' axis1.log > rpcEncoded11plainarrays-req.xml
sed -n '26p' axis1.log > rpcEncoded11plainarrays-res.xml
sed -n '27p' axis1.log > rpcEncoded11wrappedarrays-req.xml
sed -n '28p' axis1.log > rpcEncoded11wrappedarrays-res.xml
sed -n '29p' axis1.log > rpcEncoded12plainarrays-req.xml
sed -n '30p' axis1.log > rpcEncoded12plainarrays-res.xml
sed -n '31p' axis1.log > rpcEncoded12wrappedarrays-req.xml
sed -n '32p' axis1.log > rpcEncoded12wrappedarrays-res.xml
sed -n '33p' axis1.log > wrappedLiteral11plainarrays-req.xml
sed -n '34p' axis1.log > wrappedLiteral11plainarrays-res.xml
sed -n '35p' axis1.log > wrappedLiteral11wrappedarrays-req.xml
sed -n '36p' axis1.log > wrappedLiteral11wrappedarrays-res.xml
sed -n '37p' axis1.log > wrappedLiteral12plainarrays-req.xml
sed -n '38p' axis1.log > wrappedLiteral12plainarrays-res.xml
sed -n '39p' axis1.log > wrappedLiteral12wrappedarrays-req.xml
sed -n '40p' axis1.log > wrappedLiteral12wrappedarrays-res.xml
sed -n '41p' axis1.log > wrappedEncoded11plainarrays-req.xml
sed -n '42p' axis1.log > wrappedEncoded11plainarrays-res.xml
sed -n '43p' axis1.log > wrappedEncoded11wrappedarrays-req.xml
sed -n '44p' axis1.log > wrappedEncoded11wrappedarrays-res.xml
sed -n '45p' axis1.log > wrappedEncoded12plainarrays-req.xml
sed -n '46p' axis1.log > wrappedEncoded12plainarrays-res.xml
sed -n '47p' axis1.log > wrappedEncoded12wrappedarrays-req.xml
sed -n '48p' axis1.log > wrappedEncoded12wrappedarrays-res.xml
