
/**
 * Endpoint implementation, parameters and return values are POJOs written by me. _Helper classes in subpackages are generated by Axis1 Java2WSDL.
 * This package is not used to run the tests, because it was used to generate WSDL, and then WSDLs were used to generate classes again.
 */
package org.springframework.ws.axis1.case2.codefirst;

