//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.17929.
// 
namespace Axis1Case2DocumentEncoded12
{

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
	[System.Web.Services.WebServiceBindingAttribute(Name = "EchoEndpointDocumentEncoded12SoapBinding", Namespace = "http://codefirst.case2.axis1.ws.springframework.org")]
	[System.Xml.Serialization.SoapIncludeAttribute(typeof(Param3))]
	public interface IEchoEndpointDocumentEncoded12SoapBinding
	{

		/// <remarks/>
		[System.Web.Services.WebMethodAttribute()]
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("echo", RequestNamespace = "", ResponseNamespace = "", Use = System.Web.Services.Description.SoapBindingUse.Encoded, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare)]
		[return: System.Xml.Serialization.SoapElementAttribute("echoReturn")]
		Result1 echo(Param1 param, Param2 param2);
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://codefirst.case2.axis1.ws.springframework.org")]
	public partial class Param1
	{

		private sbyte[] listField;

		private System.Nullable<long> numberField;

		private Param2 param2Field;

		private Param3[] param3listField;

		private string stringField;

		/// <remarks/>
		[System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
		public sbyte[] list
		{
			get
			{
				return this.listField;
			}
			set
			{
				this.listField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
		public System.Nullable<long> number
		{
			get
			{
				return this.numberField;
			}
			set
			{
				this.numberField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
		public Param2 param2
		{
			get
			{
				return this.param2Field;
			}
			set
			{
				this.param2Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
		public Param3[] param3list
		{
			get
			{
				return this.param3listField;
			}
			set
			{
				this.param3listField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
		public string @string
		{
			get
			{
				return this.stringField;
			}
			set
			{
				this.stringField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://codefirst.case2.axis1.ws.springframework.org")]
	public partial class Param2
	{

		private System.Nullable<decimal> bdField;

		private string[] listField;

		private System.Nullable<int> numberField;

		private Param3[] param3TabField;

		/// <remarks/>
		[System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
		public System.Nullable<decimal> bd
		{
			get
			{
				return this.bdField;
			}
			set
			{
				this.bdField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
		public string[] list
		{
			get
			{
				return this.listField;
			}
			set
			{
				this.listField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
		public System.Nullable<int> number
		{
			get
			{
				return this.numberField;
			}
			set
			{
				this.numberField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
		public Param3[] param3Tab
		{
			get
			{
				return this.param3TabField;
			}
			set
			{
				this.param3TabField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://codefirst.case2.axis1.ws.springframework.org")]
	public partial class Param3
	{

		private System.Nullable<long> lvalueField;

		private string svalueField;

		/// <remarks/>
		[System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
		public System.Nullable<long> lvalue
		{
			get
			{
				return this.lvalueField;
			}
			set
			{
				this.lvalueField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
		public string svalue
		{
			get
			{
				return this.svalueField;
			}
			set
			{
				this.svalueField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://codefirst.case2.axis1.ws.springframework.org")]
	public partial class Result1
	{

		private decimal[] listField;

		private Param2 param2Field;

		private string strField;

		/// <remarks/>
		[System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
		public decimal[] list
		{
			get
			{
				return this.listField;
			}
			set
			{
				this.listField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
		public Param2 param2
		{
			get
			{
				return this.param2Field;
			}
			set
			{
				this.param2Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
		public string str
		{
			get
			{
				return this.strField;
			}
			set
			{
				this.strField = value;
			}
		}
	}

}