// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package org.tempuri.sample;

import javax.xml.rpc.*;

public interface Port02Service extends javax.xml.rpc.Service {
    public org.tempuri.sample.Port02 getPort02() throws ServiceException;
}
