// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package org.tempuri.sample;

public interface Port02 extends java.rmi.Remote {
    public java.lang.String hello(java.lang.String arg1) throws 
         java.rmi.RemoteException;
}
