sed -n '1p'  axis1.log > documentLiteral12plainarrays-req.xml
sed -n '2p'  axis1.log > documentLiteral12plainarrays-res.xml
sed -n '3p'  axis1.log > documentLiteral12wrappedarrays-req.xml
sed -n '4p'  axis1.log > documentLiteral12wrappedarrays-res.xml
sed -n '5p'  axis1.log > documentEncoded11plainarrays-req.xml
sed -n '6p'  axis1.log > documentEncoded11plainarrays-res.xml
sed -n '7p'  axis1.log > documentEncoded12plainarrays-req.xml
sed -n '8p'  axis1.log > documentEncoded12plainarrays-res.xml
sed -n '9p'  axis1.log > rpcLiteral12plainarrays-req.xml
sed -n '10p' axis1.log > rpcLiteral12plainarrays-res.xml
sed -n '11p' axis1.log > rpcLiteral12wrappedarrays-req.xml
sed -n '12p' axis1.log > rpcLiteral12wrappedarrays-res.xml
sed -n '13p' axis1.log > rpcEncoded11plainarrays-req.xml
sed -n '14p' axis1.log > rpcEncoded11plainarrays-res.xml
sed -n '15p' axis1.log > rpcEncoded12plainarrays-req.xml
sed -n '16p' axis1.log > rpcEncoded12plainarrays-res.xml
sed -n '17p' axis1.log > wrappedLiteral12plainarrays-req.xml
sed -n '18p' axis1.log > wrappedLiteral12plainarrays-res.xml
sed -n '19p' axis1.log > wrappedLiteral12wrappedarrays-req.xml
sed -n '20p' axis1.log > wrappedLiteral12wrappedarrays-res.xml
sed -n '21p' axis1.log > wrappedEncoded11plainarrays-req.xml
sed -n '22p' axis1.log > wrappedEncoded11plainarrays-res.xml
sed -n '23p' axis1.log > wrappedEncoded12plainarrays-req.xml
sed -n '24p' axis1.log > wrappedEncoded12plainarrays-res.xml
