/**
 * All classes are generated by Axis1 WSDL2Java. deploy.wsdd files contain proper class names used to configure runtime client stubs.
 * Creating merged server-config.wsdd: <code>find . -name deploy.wsdd | xargs sed -ne '/&lt;service /,/&lt;\/service/p'</code>
 */
package org.springframework.ws.axis1.case2.contractfirst;

