sed -n '1p'  axis1.log > documentEncodedEndpoint11-req1.xml
sed -n '2p'  axis1.log > documentEncodedEndpoint11-res1.xml
sed -n '3p'  axis1.log > documentEncodedEndpoint11-req2.xml
sed -n '4p'  axis1.log > documentEncodedEndpoint11-res2.xml
sed -n '5p'  axis1.log > documentEncodedEndpoint12-req1.xml
sed -n '6p'  axis1.log > documentEncodedEndpoint12-res1.xml
sed -n '7p'  axis1.log > documentEncodedEndpoint12-req2.xml
sed -n '8p'  axis1.log > documentEncodedEndpoint12-res2.xml
sed -n '9p'  axis1.log > documentLiteralEndpoint11-req1.xml
sed -n '10p' axis1.log > documentLiteralEndpoint11-res1.xml
sed -n '11p' axis1.log > documentLiteralEndpoint11-req2.xml
sed -n '12p' axis1.log > documentLiteralEndpoint11-res2.xml
sed -n '13p' axis1.log > documentLiteralEndpoint12-req1.xml
sed -n '14p' axis1.log > documentLiteralEndpoint12-res1.xml
sed -n '15p' axis1.log > documentLiteralEndpoint12-req2.xml
sed -n '16p' axis1.log > documentLiteralEndpoint12-res2.xml
sed -n '17p' axis1.log > rpcEncodedEndpoint11-req1.xml
sed -n '18p' axis1.log > rpcEncodedEndpoint11-res1.xml
sed -n '19p' axis1.log > rpcEncodedEndpoint11-req2.xml
sed -n '20p' axis1.log > rpcEncodedEndpoint11-res2.xml
sed -n '21p' axis1.log > rpcEncodedEndpoint12-req1.xml
sed -n '22p' axis1.log > rpcEncodedEndpoint12-res1.xml
sed -n '23p' axis1.log > rpcEncodedEndpoint12-req2.xml
sed -n '24p' axis1.log > rpcEncodedEndpoint12-res2.xml
sed -n '25p' axis1.log > rpcLiteralEndpoint11-req1.xml
sed -n '26p' axis1.log > rpcLiteralEndpoint11-res1.xml
sed -n '27p' axis1.log > rpcLiteralEndpoint11-req2.xml
sed -n '28p' axis1.log > rpcLiteralEndpoint11-res2.xml
sed -n '29p' axis1.log > rpcLiteralEndpoint12-req1.xml
sed -n '30p' axis1.log > rpcLiteralEndpoint12-res1.xml
sed -n '31p' axis1.log > rpcLiteralEndpoint12-req2.xml
sed -n '32p' axis1.log > rpcLiteralEndpoint12-res2.xml
sed -n '33p' axis1.log > wrappedLiteralEndpoint11-req1.xml
sed -n '34p' axis1.log > wrappedLiteralEndpoint11-res1.xml
sed -n '35p' axis1.log > wrappedLiteralEndpoint11-req2.xml
sed -n '36p' axis1.log > wrappedLiteralEndpoint11-res2.xml
sed -n '37p' axis1.log > wrappedLiteralEndpoint12-req1.xml
sed -n '38p' axis1.log > wrappedLiteralEndpoint12-res1.xml
sed -n '39p' axis1.log > wrappedLiteralEndpoint12-req2.xml
sed -n '40p' axis1.log > wrappedLiteralEndpoint12-res2.xml
